apiVersion: v1
kind: Secret
metadata:
  name: {{ include "readwillbe.fullname" . }}
  labels:
    {{- include "readwillbe.labels" . | nindent 4 }}
type: Opaque
data:
  cookie-secret: {{ .Values.secrets.cookieSecret | default (randAlphaNum 32) | b64enc | quote }}
  {{- if .Values.secrets.vapidPublicKey }}
  vapid-public-key: {{ .Values.secrets.vapidPublicKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.vapidPrivateKey }}
  vapid-private-key: {{ .Values.secrets.vapidPrivateKey | b64enc | quote }}
  {{- end }}
